### ISSUE TITLE
Mistakes in the documentation

### ISSUE THREAD

**Issue by quark67** [AliaumeL/ensps-colorscheme#1]
You show a command which doesn't exist:
<img width="665" alt="image" src="https://github.com/AliaumeL/ensps-colorscheme/assets/9338576/adc8d160-a476-4087-a331-371e23ddfb42">
`\enspscolordefs` is not defined by your package.

You also show a lot of color names wrongly, with a `\` before their names:
<img width="405" alt="image" src="https://github.com/AliaumeL/ensps-colorscheme/assets/9338576/69e715bd-9915-4711-a555-aee95712a334">
Commands `\A1bg` and so on doesn't exist (and cannot exist because of number in their name).

Also in section 3 (Implementation), you are missing:

```latex
\NeedsTeXFormat{LaTeX2e}[2023-11-01] 
\ProvidesPackage{ensps-colorscheme}
 [2024-05-03 v0.0.1 ENS Paris-Saclay Colors and Theme]
\RequirePackage{xcolor}
\RequirePackage{tikz}
```

But some packages documentation doesn't show these lines. If you show these lines, your users understand that they don't have to load `xcolor` to use your package. Instead of showing these lines, you can say that this package load xcolor (via tikz).

Moreover, if you load `tikz` you don't need to load `xcolor`, so `\RequirePackage{xcolor}` is not needed.

**Comment by AliaumeL** [comment]
Thanks a lot for your comments!

I believe all the remarks are now addressed in the commit 34076a0de52b7888199cd417791cc1e8c6543ce1. Namely:

- [x] The commands like `\A1bg` have been replaced by the actual color name `A1bg`,
- [x] The `enspscolordefs` macro documentation has been removed,
- [x] The preamble of the package is now documented,
- [x] The `xcolor` package is not required because this is implicitly loaded by `tikz`.
